Generate a clearer type assertion for arrays
By assigning to a variable with the type Array, TypeScript can give us errors like:

   Type 'string' is not assignable to type 'any'.

Rather than the error:

  Property 'every' does not exist on type 'string'.